// <auto-generated />
using Anuitex_Test.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Anuitex_Test.Migrations
{
    [DbContext(typeof(AnuitexContext))]
    [Migration("20201021152527_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Anuitex_Test.Models.Company", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Anuitex_Test.Models.Employee", b =>
                {
                    b.Property<string>("FullName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Experience")
                        .HasColumnType("int");

                    b.HasKey("FullName");

                    b.HasIndex("CompanyName");

                    b.ToTable("Employees");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Employee");
                });

            modelBuilder.Entity("Anuitex_Test.Models.Brigadier", b =>
                {
                    b.HasBaseType("Anuitex_Test.Models.Employee");

                    b.HasDiscriminator().HasValue("Brigadier");
                });

            modelBuilder.Entity("Anuitex_Test.Models.Manager", b =>
                {
                    b.HasBaseType("Anuitex_Test.Models.Employee");

                    b.HasDiscriminator().HasValue("Manager");
                });

            modelBuilder.Entity("Anuitex_Test.Models.Worker", b =>
                {
                    b.HasBaseType("Anuitex_Test.Models.Employee");

                    b.HasDiscriminator().HasValue("Worker");
                });

            modelBuilder.Entity("Anuitex_Test.Models.Employee", b =>
                {
                    b.HasOne("Anuitex_Test.Models.Company", null)
                        .WithMany("Employees")
                        .HasForeignKey("CompanyName");
                });
#pragma warning restore 612, 618
        }
    }
}
